project:
  type: website

website:
  title: "Pitch Deck"

format:
  html:
    theme: [sketchy]  # try: default, vapor, sketchy (https://bootswatch.com/sketchy/)
    execute:
      echo: false  # prevents the Python code from being shown while still executing it and displaying the output.
