project:
  type: website

website:
  title: "Pitch Deck"

format:
  html:
    theme: [quartz, custom.scss]
    execute:
      echo: false  # prevents the Python code from being shown while still executing it and displaying the output.
