name: Quarto Publish

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: quarto-dev/quarto-actions/setup@v2

      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: quarto-env
          environment-file: environment.yml
          auto-activate-base: false

      - name: Register kernel
        shell: bash -l {0}
        run: |
          python -m ipykernel install --user --name quarto-env

      - name: Force Quarto to use conda Python
        shell: bash -l {0}
        run: |
          echo "QUARTO_PYTHON=$(which python)" >> $GITHUB_ENV

      - name: Render
        shell: bash -l {0}
        run: quarto render

      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          render: false
